#!/usr/bin/env python3

import rospy
from snakelib_hebi.hebi_sensor_interface import HEBISensingROSWrapper


if __name__ == "__main__":
    rospy.init_node("hebi_sensor_interface", anonymous=False)
    hebi_interface = HEBISensingROSWrapper()
    try:
        hebi_interface.start()
    except rospy.ROSInterruptException:
        pass