#!/usr/bin/env python3

import rospy
from snakelib_hebi.hebi_control_interface import HEBIControlROSWrapper


if __name__ == "__main__":
    rospy.init_node("hebi_control_interface", anonymous=False)
    HEBIControlROSWrapper()