#!/usr/bin/env python3

import rospy
from snakelib_hebi.snake_state_visualizer import SnakeStateVisualizer


if __name__ == "__main__":
    rospy.init_node("visualization_interface", anonymous=False)
    visualization_interface = SnakeStateVisualizer()
    try:
        visualization_interface.start()
    except rospy.ROSInterruptException:
        pass
