#!/usr/bin/env python

import signal
import sys

import rospy
from PyQt5.QtWidgets import QApplication
from PyQt5 import QtCore
from snakelib_gui.gui import SignalWakeupHandler, SnakeViz

if __name__ == '__main__':
    rospy.init_node("SnakeLib_GUI", anonymous=False)
    app = QApplication( sys.argv )

    snake_viz = SnakeViz(app)
    snake_viz.showMaximized()

    SignalWakeupHandler(snake_viz.frame)
    signal.signal(signal.SIGINT, lambda sig,_: app.quit())

    app.exec_()
    app.closeAllWindows()
