#!/usr/bin/env python

import rospy
from snakelib_camera.usb_camera_interface import FisheyeCameraStreamer


if __name__ == "__main__":
    rospy.init_node("fisheye_node", anonymous=False)
    camera_interface = FisheyeCameraStreamer()
    try:
        camera_interface.start()
    except rospy.ROSInterruptException:
        pass