#!/usr/bin/env python

import rospy
from snakelib_camera.image_processing import ImageProcessor


if __name__ == "__main__":
    rospy.init_node("image_processing_node", anonymous=False)
    camera_interface = ImageProcessor()
    try:
        camera_interface.start()
    except rospy.ROSInterruptException:
        pass